# -----------------------------------------------------------------
#                FICHIER DE CONFIGURATION DECAP CMS
# -----------------------------------------------------------------
# Ce fichier doit être indenté avec des espaces, PAS des tabulations.

# Backend: On dit au CMS de se connecter directement via GitHub.
backend:
  name: github
  repo: michaeldev83/jdr # Assure-toi que c'est bien ton repo
  branch: main

# Media: On dit au CMS où stocker les fichiers que l'on uploade par défaut.
media_folder: "assets/images"
public_folder: "/assets/images"

# Collections: On définit le contenu éditable.
collections:
  - name: "pages"
    label: "Contenu du Site"
    files:
      - name: "games"
        label: "Jeux de Rôle"
        file: "data.json"
        # On dit que le fichier data.json est une liste directement
        widget: "list"
        # Et voici les champs pour UN élément de cette liste
        fields:
          - { label: "Nom du Jeu", name: "name", widget: "string" }
          - { label: "ID Unique", name: "id", widget: "string", hint: "Identifiant court sans espaces ni accents (ex: dnd5, shadowrun5)." }
          - { label: "Image de la Vignette", name: "image", widget: "image" }
          - label: "Documents"
            name: "documents"
            widget: "list"
            fields:
              - { label: "Titre du document", name: "title", widget: "string" }
              - label: "Fichier (PDF, etc.)"
                name: "file"
                widget: "file"
                media_folder: "assets/docs"
                public_folder: "/assets/docs"