# Backend
backend:
  name: github
  repo: michaeldev83/jdr # Vérifie que c'est toujours bon
  branch: main

# Media
media_folder: "assets/images"
public_folder: "/assets/images"

# Collections
collections:
  - name: "pages"
    label: "Contenu du Site"
    files:
      - name: "games_file" # Nom technique, peu importe
        label: "Jeux de Rôle"
        file: "data.json"
        # On décrit maintenant les champs du fichier. Le premier est "games".
        fields:
          - name: "games" # <-- ICI, on cible la clé "games" dans le JSON
            label: "Liste des Jeux"
            widget: "list"
            # Et voici les champs pour UN élément de cette liste
            fields:
              - { label: "Nom du Jeu", name: "name", widget: "string" }
              - { label: "ID Unique", name: "id", widget: "string", hint: "Identifiant court sans espaces ni accents (ex: dnd5)." }
              - { label: "Image de la Vignette", name: "image", widget: "image" }
              - label: "Documents"
                name: "documents"
                widget: "list"
                fields:
                  - { label: "Titre du document", name: "title", widget: "string" }
                  - label: "Fichier (PDF, etc.)"
                    name: "file"
                    widget: "file"
                    media_folder: "assets/docs"
                    public_folder: "/assets/docs"
          - name: "app" # <-- ICI, on cible la clé "games" dans le JSON
            label: "Liste des applications"
            widget: "list"
            # Et voici les champs pour UN élément de cette liste
            fields:
              - { label: "Nom de l'application", name: "name", widget: "string" }
              - { label: "ID Unique", name: "id", widget: "string", hint: "Identifiant court sans espaces ni accents (ex: dnd5)." }
              - { label: "URL", name: "Url_app", widget: "string", hint: "Entrez l'URL du site (ex. https://example.com)" }